### ISSUE TITLE
Remove old files upon plugin update

### ISSUE THREAD

**Issue by samuelvogel** [VIISON/shopware-4#18]
We ran in problem multiple times already because of old plugin files still being present. Currently the [plugin ZIP is simply extracted](https://github.com/shopware/shopware/blob/27507fe404cede0b75ad561fc081ce4fc9554569/engine/Shopware/Bundle/PluginInstallerBundle/Service/DownloadService.php#L101-L126) over the already existing plugin, thereby overwriting all files but not removing anything that was already there before.

**Comment by svenmuennich** [comment]
Since a PR with shopware won't really help us anyway, we should probably generate some kind of *summary* file in the release script, wich contains the relative paths of every plugin file. Then we could add a class to *ShopwareCommon* removes all files that are not part of the summary, if a summary is available.
