### ISSUE TITLE
Allow translation of plugin configurations select values

### ISSUE THREAD

**Issue by samuelvogel** [VIISON/shopware-4#46]
Currently it's not possible to translate the values of select inputs in the plugin config:
![config-selects](https://user-images.githubusercontent.com/710188/30850461-e6bcc8bc-a2a5-11e7-98ba-f29353161b34.png)

**Comment by fixpunkt** [comment]
Turns out this is actually implemented already, just well-hidden:

https://github.com/shopware/shopware/blob/28a3689112757c41914f6b403b17b2880e269e7a/engine/Shopware/Controllers/Backend/Config.php#L904-L946

**Comment by fixpunkt** [comment]
Turns out Shopware actually broke this in 5.3:
https://github.com/VIISON/shopware/commit/db7b41e813b456e081576e222130d9482d384ae2#diff-82dab508fe5ae6234ffc4ea20d371fc8R187

This line causes the loaded store translations to be overwritten by the default, so config store translation breaks completely.

**Comment by fixpunkt** [comment]
PR is here: https://github.com/shopware/shopware/pull/1289
