### ISSUE TITLE
PR: Make document type names and number ranges translatable

### ISSUE THREAD

**Issue by fixpunkt** [VIISON/shopware-4#47]
Document type names are already translatable, but the translation is not displayed in the PDF document generation config. Number ranges are not translatable at all:

![image](https://user-images.githubusercontent.com/2817302/31288298-9aaa5cce-aac4-11e7-8c1c-f55dc69f28c6.png)

We should make a PR that:

1. Makes the "PDF document creation" settings page show the translated names of the document types
2. Adds translations for all Shopware default document types
3. Adds translations for all Shopware default number ranges
4. Shows the translated names for the number ranges in the settings page

**Comment by samuelvogel** [comment]
Feedback after discussing with @niklasbuechner:
1. If we do this, we need to take care of shipping and payment methods (and probably some other places as well) to have this in a consistent manner.
2. Already present in the Shopware default data set.
3. Number ranges are currently not really translatable, so we need to add translatability first and then the data to fill it.

Numbers 3 & 4 are actually the main goal in my opinion as well as adding a identifier to the document type table to make our Pickware ERP supplier order management more robust to document name changes.

**Comment by samuelvogel** [comment]
We (@svenmuennich, @fixpunkt, @niklasbuechner and me) just discussed this again and decided:
1. Making number ranges translatable is not big issue as they are only visible in the number ranges and document configuration (not in any real world use case except pure configuration).
2. Our fokus for now is not to show the translated wording in the configuration of documents, shipping & payment methods and number ranges. This is nice to have but only really applies to our special demo shop setup (with a two language backend) and in live-demos the configuration is never shown either.
3. We will make sure the name of a document can be changed, because that's what most englisch users of the backend will do, see: https://github.com/VIISON/shopware/pull/50
4. We will check if documents, shipping & payment methods are translated everywhere they are actually used outside of their respective configuration. @fixpunkt suspects that this is at least problematic for non-standard document types (if this is the case a fix can be built upon 3.).

**Comment by niklasbuechner** [comment]
The only place without translation I found, is in the order detail overview.

![screen shot 2017-10-18 at 10 24 36](https://user-images.githubusercontent.com/31041526/31708245-bc6dbea4-b3ee-11e7-9fb5-eeb5a6740783.png)

I will go ahead and implement the translation.

**Comment by niklasbuechner** [comment]
To correct the previous comment, there are more places where the translations is missing:
1. Order list filter panel
![screen shot 2017-10-18 at 11 18 52](https://user-images.githubusercontent.com/31041526/31710771-4f950744-b3f6-11e7-8541-752ee5a60cae.png)

2. Order list:
![screen shot 2017-10-18 at 11 19 05](https://user-images.githubusercontent.com/31041526/31710780-575f223e-b3f6-11e7-87aa-3710b4b3910d.png)

3. The order list of a customer:
![screen shot 2017-10-18 at 11 22 21](https://user-images.githubusercontent.com/31041526/31710903-b0ca2634-b3f6-11e7-9387-aba8c6aff2b5.png)


4. As well as the frontend:
![screen shot 2017-10-18 at 11 15 42](https://user-images.githubusercontent.com/31041526/31710797-683ae2c8-b3f6-11e7-98d3-fd5837c86cb1.png)

**Comment by samuelvogel** [comment]
Are you really sure that shipping method translations don't work in the frontend @niklasbuechner?

**Comment by niklasbuechner** [comment]
@samuelvogel The translation mechanism is working correctly in the frontend, however, Shopware does not come with translations for the shipping methods. I will therefore add standard translations for the methods as fix.

**Comment by niklasbuechner** [comment]
I added the functionality and opened the PR against the official Shopware repository: https://github.com/shopware/shopware/pull/1493
