### ISSUE TITLE
Shared Doctrine metadata cached in APCu shared between Shopware instances

### ISSUE THREAD

**Issue by samuelvogel** [VIISON/shopware-4#64]
Another idea why `Property Shopware\... does not exist` exceptions occur with multiple Shopware instances (e.g. live & test) on the same server: The Doctrine metadata cache resides in APCu and the key used to retrieve it is always the same.

If different plugin versions are run in these Shopware instances which have different attribute models the exception might randomly occur because of the shared cache.

We should check this assumption and write a PR (to add a per instance prefix to the cache keys) for this if turns out to be a problem!

**Comment by svenmuennich** [comment]
We checked the code and apparently [the cache `namespace` is constructed from the configured path of the cache directory and the Shopware version, both concatenated and `md5`ed](https://github.com/shopware/shopware/blob/f3f67b7aa6dccc06bdb9c215ad2f8367effdd886/engine/Shopware/Components/Model/Configuration.php#L124-L128). So when installing a production and staging shop on the same server the `namespace` will be different due to the different paths. Hence there should not be any corrupt caches.

We can also assume that in shared hosting, where the namespace might be the same for different shops, neither `APC` nor `APCu` are enabled because of security concerns.
